---

- name: Deploy HAProxy
  hosts: frontends
  gather_facts: false
  become: true

  roles:
    - prereq
    - haproxy

- name: Deploy application
  hosts: apps
  gather_facts: false
  become: true

  roles:
    - application